#!/usr/bin/env bash
# Rename the crate across every tracked file that carries the template's
# identifiers (`rust-app-template`, `rust_app_template`).
#
# Usage: bash scripts/bulk-rename.sh <snake_case_name> <kebab-case-name>
#
# Strategy: enumerate tracked files via `git ls-files`, grep for the template
# identifiers, and run sed on the matching set. This is more robust than a
# hardcoded file list — a previous version of this script missed
# `src/**/*.rs`, `tests/**/*.rs`, `k8s/overlays/**/*.yaml`, and any new file
# type introduced later.
#
# Excluded from rewriting: this script itself (contains the source identifiers
# as sed patterns), and lockfiles (regenerated by tooling).
set -euo pipefail

if [ $# -ne 2 ]; then
    echo "Usage: $0 <snake_case_name> <kebab-case-name>" >&2
    exit 1
fi

SNAKE="$1"
KEBAB="$2"

mapfile -t FILES < <(
    git ls-files \
        | grep -v '^scripts/bulk-rename\.sh$' \
        | grep -v '^MODULE\.bazel\.lock$' \
        | grep -v '^Cargo\.lock$' \
        | grep -v '^frontend/pnpm-lock\.yaml$' \
        | xargs grep -l -E 'rust-app-template|rust_app_template' 2>/dev/null || true
)

if [ ${#FILES[@]} -eq 0 ]; then
    echo "No files contain the template identifiers. Already renamed?" >&2
    exit 0
fi

for f in "${FILES[@]}"; do
    # Portable across GNU and BSD sed via the -i.bak idiom.
    sed -i.bak \
        -e "s/rust-app-template/${KEBAB}/g" \
        -e "s/rust_app_template/${SNAKE}/g" \
        "$f"
    rm -f "$f.bak"
done

echo "Renamed ${#FILES[@]} files to snake='${SNAKE}', kebab='${KEBAB}'." >&2

# Renaming can shift import ordering (e.g. `proptest` vs a new crate name that
# sorts before it), so run rustfmt to normalize. Skip silently if cargo isn't
# on PATH — the rename itself is still valid.
if command -v cargo >/dev/null 2>&1; then
    echo "Running 'cargo fmt' to normalize import ordering..." >&2
    cargo fmt
fi

echo "Regenerate lockfiles if needed:" >&2
echo "  just bazel-repin" >&2
echo "  (cd frontend && pnpm install)" >&2
echo "Review 'git diff' before committing." >&2
